export {};

const read = (path: string) => Bun.file(path).text();
type PermissionEntry = string | {
  identifier: string;
  allow?: Array<Record<string, unknown>>;
};
const permissionIdentifier = (permission: PermissionEntry): string =>
  typeof permission === 'string' ? permission : permission.identifier;

const [buildSource, libSource, tauriConfig] = await Promise.all([
  read('src-tauri/build.rs'),
  read('src-tauri/src/lib.rs'),
  Bun.file('src-tauri/tauri.conf.json').json() as Promise<{
    app?: { security?: { capabilities?: string[] } };
  }>,
]);

const buildBlock = buildSource.match(/\.commands\(&\[([\s\S]*?)\]\)/)?.[1] ?? '';
const buildCommands = new Set([...buildBlock.matchAll(/"([a-z][a-z0-9_]*)"/g)].map((match) => match[1]));
const handlerBlock = libSource.match(/generate_handler!\[([\s\S]*?)\]\)/)?.[1] ?? '';
const handlerCommands = new Set([...handlerBlock.matchAll(/(?:\w+::)+(\w+)/g)].map((match) => match[1]));

const capabilityFiles = [
  'src-tauri/capabilities/main-runtime.json',
  'src-tauri/capabilities/local-reader.json',
  'src-tauri/capabilities/settings.json',
  'src-tauri/capabilities/plugin-editor.json',
  'src-tauri/capabilities/plugin-installer.json',
  'src-tauri/capabilities/legal-documents.json',
];
const capabilityCommands = new Set<string>();
const capabilityIdentifiers = new Set<string>();
let mainRuntimePermissions: PermissionEntry[] = [];
let localReaderPermissions: PermissionEntry[] = [];
for (const file of capabilityFiles) {
  const capability = await Bun.file(file).json() as {
    identifier?: string;
    permissions?: PermissionEntry[];
    windows?: string[];
  };
  if (capability.identifier) capabilityIdentifiers.add(capability.identifier);
  if (file.endsWith('main-runtime.json')) {
    mainRuntimePermissions = capability.permissions ?? [];
  }
  if (file.endsWith('local-reader.json')) {
    localReaderPermissions = capability.permissions ?? [];
  }
  for (const permission of capability.permissions ?? []) {
    const identifier = permissionIdentifier(permission);
    if (identifier.startsWith('allow-')) {
      capabilityCommands.add(identifier.slice(6).replaceAll('-', '_'));
    }
  }
}

const permissionFiles = new Bun.Glob('*.toml');
const generatedCommands = new Set<string>();
for await (const file of permissionFiles.scan('src-tauri/permissions/autogenerated')) {
  generatedCommands.add(file.replace(/\.toml$/, ''));
}

const difference = (left: Set<string>, right: Set<string>) =>
  [...left].filter((value) => !right.has(value)).sort();
const failures = [
  ['build.rs only', difference(buildCommands, handlerCommands)],
  ['generate_handler only', difference(handlerCommands, buildCommands)],
  ['missing capability', difference(handlerCommands, capabilityCommands)],
  ['capability without handler', difference(capabilityCommands, handlerCommands)],
  ['missing generated permission', difference(handlerCommands, generatedCommands)],
  ['stale generated permission', difference(generatedCommands, handlerCommands)],
] as const;

const messages = failures
  .filter(([, values]) => values.length > 0)
  .map(([label, values]) => `${label}: ${values.join(', ')}`);
const configuredCapabilities = new Set(tauriConfig.app?.security?.capabilities ?? []);
const missingConfiguredCapabilities = difference(capabilityIdentifiers, configuredCapabilities);
const unknownConfiguredCapabilities = difference(configuredCapabilities, capabilityIdentifiers);
if (missingConfiguredCapabilities.length > 0) {
  messages.push(`capability file not enabled: ${missingConfiguredCapabilities.join(', ')}`);
}
if (unknownConfiguredCapabilities.length > 0) {
  messages.push(`configured capability file missing: ${unknownConfiguredCapabilities.join(', ')}`);
}
const mainRuntimePermissionIdentifiers = mainRuntimePermissions.map(permissionIdentifier);
const localReaderPermissionIdentifiers = localReaderPermissions.map(permissionIdentifier);
const forbiddenMainPermissions = mainRuntimePermissionIdentifiers.filter((permission) =>
  /(?:fs|shell|updater|dialog|opener|create)/i.test(permission)
  || /allow-(?:install|uninstall|get-installed|load-plugin-for-edit|save-plugin|export-plugin)/.test(permission)
);
if (forbiddenMainPermissions.length > 0) {
  messages.push(`dangerous main-runtime permission: ${forbiddenMainPermissions.join(', ')}`);
}
// 远程主窗口的 core: 权限白名单：core:default（window 部分仅只读查询）与
// core:event:default 已知安全；其余 core 权限（如 core:window:allow-set-theme）
// 必须显式加入白名单并评估 scope 限定（如限定 label）后方可授予远程页面，
// 否则远程页面可向任意窗口发起该命令。
const allowedMainCorePermissions = new Set([
  'core:default',
  'core:event:default',
  'core:window:allow-set-theme',
]);
const unexpectedMainCorePermissions = mainRuntimePermissionIdentifiers.filter(
  (permission) => permission.startsWith('core:') && !allowedMainCorePermissions.has(permission),
);
if (unexpectedMainCorePermissions.length > 0) {
  messages.push(`unexpected core permission in main-runtime (extend allowlist consciously): ${unexpectedMainCorePermissions.join(', ')}`);
}
const setThemePermission = mainRuntimePermissions.find(
  (permission) => permissionIdentifier(permission) === 'core:window:allow-set-theme',
);
const setThemeScope = typeof setThemePermission === 'object' ? setThemePermission.allow : undefined;
if (
  !setThemeScope
  || setThemeScope.length !== 1
  || setThemeScope[0]?.label !== 'main'
) {
  messages.push('main-runtime set-theme permission must allow only label main');
}
const expectedMainCommands = new Set([
  'log_to_file',
  'update_menu_state',
  'set_menu_item_enabled',
  'set_active_bookstore',
  'set_title',
  'toggle_stealth',
  'toggle_menu_bar',
  'reveal_menu_bar_transient',
  'is_main_fullscreen',
  'simulate_menu_click',
  'switch_bookstore_by_index',
  'apply_site_zoom',
  'get_app_name',
  'get_settings',
  'patch_settings',
  'get_reading_position',
  'save_reading_position',
  'get_runtime_plugin',
]);
const mainCommands = new Set(
  mainRuntimePermissionIdentifiers
    .filter((permission) => permission.startsWith('allow-'))
    .map((permission) => permission.slice(6).replaceAll('-', '_')),
);
const missingMainCommands = difference(expectedMainCommands, mainCommands);
const unexpectedMainCommands = difference(mainCommands, expectedMainCommands);
if (missingMainCommands.length > 0) {
  messages.push(`main-runtime missing command: ${missingMainCommands.join(', ')}`);
}
if (unexpectedMainCommands.length > 0) {
  messages.push(`main-runtime unexpected command: ${unexpectedMainCommands.join(', ')}`);
}
const expectedLocalCommands = new Set([
  'log_to_file',
  'update_menu_state',
  'set_menu_item_enabled',
  'set_active_bookstore',
  'set_title',
  'toggle_menu_bar',
  'simulate_menu_click',
  'switch_bookstore_by_index',
  'apply_site_zoom',
  'get_app_name',
  'get_settings',
  'patch_settings',
  'get_local_book',
  'get_local_reading_progress',
  'save_local_reading_progress',
  'local_sha1',
]);
const localCommands = new Set(
  localReaderPermissionIdentifiers
    .filter((permission) => permission.startsWith('allow-'))
    .map((permission) => permission.slice(6).replaceAll('-', '_')),
);
const missingLocalCommands = difference(expectedLocalCommands, localCommands);
const unexpectedLocalCommands = difference(localCommands, expectedLocalCommands);
if (missingLocalCommands.length > 0) {
  messages.push(`local-reader missing command: ${missingLocalCommands.join(', ')}`);
}
if (unexpectedLocalCommands.length > 0) {
  messages.push(`local-reader unexpected command: ${unexpectedLocalCommands.join(', ')}`);
}
if (messages.length > 0) {
  console.error(`IPC consistency check failed:\n${messages.join('\n')}`);
  process.exit(1);
}
console.log(`IPC consistency verified for ${handlerCommands.size} commands.`);
